language: python
python: 3.6

stages:
- lint readme
- deploy package

jobs:
  include:

  - stage: lint readme
    install:
    - pip install twine
    script:
    - python setup.py -q sdist bdist_wheel
    - twine check dist/*

  - stage: deploy package
    install: skip
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: bittner
      password:
        secure: bjU1AfMX/fzvBdBA1kcTZIpFoc8cQw7WnVrflSesS452rueiS+aXEk9uFaGTXffWJdP793tmkLMQh1b1hwkwC5GCNf+tEHop9E4A6n+6IS0tDAuApcRCbrIlENhzyR/yNnsBOY6aa0KpVwOFMS94SMlT+q8ZkEw4IQHcNaej9ys=
      on:
        tags: true
